name: Create release

on:
  workflow_dispatch:
    inputs:
      releaseMessage:
        required: true
        description: The message posted to the release.

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifact

      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: ${{ fromJSON(needs.build.outputs.gitversion).MajorMinorPatch }}
          name: Release ${{ fromJSON(needs.build.outputs.gitversion).MajorMinorPatch }}
          body: "${{ github.event.inputs.releaseMessage }}"
          files: |
            SpectatorDisabler-Exiled-${{ fromJSON(needs.build.outputs.gitversion).AssemblySemVer }}.zip
            SpectatorDisabler-LabApi-${{ fromJSON(needs.build.outputs.gitversion).AssemblySemVer }}.zip
